
DROP TABLE IF EXISTS UserPosts;
DROP TABLE IF EXISTS CollectiveMembers;
DROP TABLE IF EXISTS Collective;
DROP TABLE IF EXISTS Followers;
DROP TABLE IF EXISTS Notifications;
DROP TABLE IF EXISTS Likes;
DROP TABLE IF EXISTS Comments;
DROP TABLE IF EXISTS Posts;
DROP TABLE IF EXISTS Users;


